export const ROLE_PERMISSIONS = {
  student: {
    canCreate: true,
    canEditOwn: true,
    canUpdate: true,
    canDeleteOwn: true,
    canDelete: false,
    canViewAll: false,
    canAssign: false,
    canResolve: false,
    viewMode: "cards",
    // canComment: true,
    // canDownload: false,
  },

  lab_assistant: {
    canCreate: false,
    canEditAll: true,
    canUpdate: true,
    canDelete: false,
    canViewAll: true,
    canAssign: true,
    canResolve: true,
    viewMode: "table",
    // canComment: true,
    // canDownload: true,
  },

  moderator: {
    canCreate: false,
    canEditAll: true,
    canUpdate: true,
    canDelete: false,
    canViewAll: true,
    canAssign: false,
    canResolve: true,
    viewMode: "table",
    // canComment: true,
    // canDownload: true,
  },

  admin: {
    canCreate: true,
    canEditAll: true,
    canUpdate: true,
    canDelete: true,
    canViewAll: true,
    canAssign: true,
    canResolve: true,
    viewMode: "cards",
    // canComment: true,
    // canDownload: true,
    // canManageRoles: true, 
    // canAccessSettings: true, 
  },
};
